### PR TITLE
Learning positioning

### PR DESCRIPTION
**Pull request by tiagorahal**
Did the page using Flex and Grid, using the correct semantic HTML.
The objective of this project is to clone a New York Times article page, the links on that project will not redirect to the links in the original page, some fonts are not the same either as a lot of them are paid fonts, I was able to get all the images from the original page.
I worked on a 1920x1080 screen doing this project.

### CODE REVIEW

**Review by trekab — CHANGES_REQUESTED** [review]
### Changes Required! :recycle: 
Hi @tiagorahal! Your work so far looks good! I like that you have made good use of `float`, `flex`, `grid`, and semantic HTML. However, there are a few issues for  you to fix to complete this project;
- [ ] Add a brief description to your Pull Request ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/general/descriptive_prs.png) from [Pathwright](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/))
- [ ] The bottom sections i.e. `Suggested newsletters for you`, `More in Space and Astronomy`, and `Editors’ Picks` could use some more styling. e.g:

__Your clone's "More in space and Astronomy" section:__
Your Page

__The original "More in space and Astronomy" section:__
Original

__Kindly make the necessary changes and submit another code review request.__
_Feel free to reach me on slack for any inquiries about this review._ :wink: 
__Treasure Kabareebe__
[Portfolio](https://trekab.github.io/portfolio/) | [LinkedIn](https://www.linkedin.com/in/treasure-kabareebe/) | [Twitter](https://twitter.com/TKabareebe)

**Comment by tiagorahal** [comment]
Thank you for the feedback, I just do not understand why the flex in the "More in space and Astronomy" is scrambled, I will post how it is appearing to me.
2021-02-17 16_26_49-Space Ripples Reveal Big Bang's Smoking Gun

**Comment by trekab** [comment]
Thanks for posting the way it appears on your screen! :+1: Please include this little detail when you submit your next code review request. Try to include your screen dimensions as well so that the reviewer can relate to your situation. This shouldn't stop your project from being approved!

**Comment by tiagorahal** [comment]
Did the page using Flex and Grid, using the correct semantic HTML.
The objective of this project is to clone a New York Times article page, the links on that project will not redirect to the links in the original page, some fonts are not the same either as a lot of them are paid fonts, I was able to get all the images from the original page.
I worked on a 1920x1080 screen doing this project.

**Review by blackpintz — APPROVED** [review]
# Status: Approved 🎉 

**Congratulations team 👏, and good luck with your next project 😃.**

**Pull request merged**
